### ISSUE TITLE
change assert is_controller_okay to log.warn and count the error

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#192]
I think that we should not get that exception and instead log the error and count one more circuit error (if it is not already being count, i've not checked).
@pastly: if it easy for you, would you do it?, otherwise i'll check:

```
[2018-06-15 16:58:51,788] [sbws.core.scanner] [ERROR] Unhandled exception in worker thread
Traceback (most recent call last):
  File "/path/simple-bw-scanner/sbws/core/scanner.py", line 257, in dispatch_worker_thread
    return measure_relay(*a, **kw)
  File "/path/simple-bw-scanner/sbws/core/scanner.py", line 170, in measure_relay
    cb.controller, conf.getfloat('general', 'http_timeout'))
  File "/path/simple-bw-scanner/sbws/util/requests.py", line 7, in make_session
    socks_info = stem_utils.get_socks_info(controller)  
  File "/path/simple-bw-scanner/sbws/util/stem.py", line 197, in get_socks_info
    assert is_controller_okay(controller)
AssertionError
```

Also:

```
Traceback (most recent call last):
  File "/path/.virtualenvs/simplebwscanner3/bin/sbws", line 11, in <module>
    load_entry_point('sbws', 'console_scripts', 'sbws')()
  File "/path/simple-bw-scanner/sbws/sbws.py", line 51, in main
    exit(comm['f'](*comm['a'], **comm['kw']))
  File "/path/simple-bw-scanner/sbws/core/scanner.py", line 402, in main
    run_speedtest(args, conf)
  File "/path/simple-bw-scanner/sbws/core/scanner.py", line 362, in run_speedtest
    for target in rp.best_priority():
  File "/path/simple-bw-scanner/sbws/lib/relayprioritizer.py", line 49, in best_priority
    relays = copy.deepcopy(self.relay_list.relays)
  File "/path/simple-bw-scanner/sbws/lib/relaylist.py", line 132, in relays
    self._refresh()
  File "/path/simple-bw-scanner/sbws/lib/relaylist.py", line 175, in _refresh
    self._relays = self._init_relays()
  File "/path/simple-bw-scanner/sbws/lib/relaylist.py", line 169, in _init_relays
    assert stem_utils.is_controller_okay(c)
```

**Comment by juga0** [comment]
Oh, and if ``stem`` gives any other information about that issue, we should probably rather log that

**Comment by pastly** [comment]
If the controller is no longer okay, then Tor probably died or some other really bad thing happened such that we will no longer be able to do useful work. Working with that assumption, I don't think we should count this as a circuit error for the relay (we'll probably start giving every relay a circuit error until the operator notices his logs and intervenes).

Do you know why your controller is no longer okay? Why these tracebacks happened?

@atagar has suggested that we don't need `is_controller_okay` and should just let stem try to use a broken controller and throw an exception itself. I think he's probably right.

**Comment by juga0** [comment]
Matt Traudt:
> If the controller is no longer okay, then Tor probably died or some other really bad thing happened such that we will no longer be able to do useful work. Working with that assumption, I don't think we should count this as a circuit error for the relay (we'll probably start giving every relay a circuit error until the operator notices his logs and intervenes).

it's fine if every relay have a circuit error, that's what we want to
find out counting errors, don't we?
And if this is not a circuit error (i'm not sure we i thought that),
then we could count it as "misc" error.

> 
> Do you know why your controller is no longer okay? Why these tracebacks happened?

nop, just got that traceback, after the 1st sbws continued measuring
other relays, after the 2nd sbws died.

> 
> @atagar has suggested that we don't need `is_controller_okay` and should just let stem try to use a broken controller and throw an exception itself. I think he's probably right.

if we let the controller throw an exception, we might get some more info
about why is not ok, what is useful at least for debugging, and later we
can change that to something more suitable

**Comment by juga0** [comment]
self-assigning since i'm changing the code for a tentative solution to this
