### ISSUE TITLE
Raised IndexError when choosing exits in test network

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#211]
Running sbws 09691a0fe7b3809f2cdacd7713c2b37668c6c93b with python 3.5.3 in the test network got this traceback:

```
    i = self._randbelow(len(seq))
  File " /path/.virtualenvs/simplebwscanner3/lib/python3.5/random.py", line 239, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
  File " /path/.virtualenvs/simplebwscanner3/lib/python3.5/random.py", line 663, in getrandbits
    raise ValueError('number of bits must be greater than zero')
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File " /path/simple-bw-scanner/sbws/core/scanner.py", line 257, in dispatch_worker_thread
    return measure_relay(*a, **kw)
  File " /path/simple-bw-scanner/sbws/core/scanner.py", line 172, in measure_relay
    dest = destinations.next()
  File " /path/simple-bw-scanner/sbws/lib/destination.py", line 245, in next
    self._perform_usability_test()
  File " /path/simple-bw-scanner/sbws/lib/destination.py", line 193, in _perform_usability_test
    exit = self._rng.choice(exits)
  File " /path/.virtualenvs/simplebwscanner3/lib/python3.5/random.py", line 264, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
[2018-06-23 13:55:54,511] [sbws.core.scanner] [ERROR] Unhandled exception caught while measuring foo: <class 'IndexError'> Cannot choose from an empty sequence
```
It seems we should check that there's at least 1 exit

**Comment by pastly** [comment]
If there isn't at least one exit in the network, we won't be able to perform measurements. If there's a very low number of exits in the network, we may have a hard time finding one.

What do you suggest as a solution?

I could see one solution being to add another ResultError type that has a very high [freshness reduction factor](https://github.com/pastly/simple-bw-scanner/blob/e3355d1c567473822c569af8bb5e34f12cee3068/sbws/lib/resultdump.py#L312) so that we try to measure the relay again soon in the future.

**Comment by juga0** [comment]
> What do you suggest as a solution?

Possible solutions would be:
1. log a warning and keep sbws running. This would be useful to don't have to monitor sbws and launch it again/
2. log a warning and exit. 
Not sure right now what would be best

> I could see one solution being to add another ResultError type that has a very high freshness reduction factor so that we try to measure the relay again soon in the future.

In this case i think was caused because losing consensus, and it might take days to come back. So probably is not needed to increment the freshness factor. Since this is unlikely to happen in Tor network, i also think it is not needed to create a new ResultError

**Comment by teor2345** [comment]
The Tor network occasionally loses consensus.

If that happens, we want sbws to log a warning, and keep running. (sbws shouldn't log too many warnings, because that can fill up the disk.)

**Comment by juga0** [comment]
ok, i'm going to solve the exception, then see if we need what @pastly comments re. freshness.

**Comment by juga0** [comment]
Checking that there's at least one exit and if not exit the loop, gives this log:
```
[2018-06-25 11:00:16,472] [sbws.lib.destination] [DEBUG] Perform usability tests
[2018-06-25 11:00:16,483] [sbws.lib.destination] [WARNING] There are no exits to perform usability tests.
[2018-06-25 11:00:16,484] [sbws.lib.destination] [DEBUG] 0/1 of our configured destinations are usable at this time
[2018-06-25 11:00:16,484] [sbws.lib.destination] [WARNING] Of our 1 configured destinations, none are usable at this time. Sleeping 300.000100 seconds on this blocking call to DestinationList.next() until we can check for a usable destination again.
```
I'm now checking that there *is* consensus in the testnet, so i'm not sure now what it's causing not having exits.

**Comment by juga0** [comment]
Created PR #220 to merge the code that generated previous log.
We may need to create a different issue to understand why we don't have exits
